flags: {}
packages:
- '.'
- location:
    git: https://github.com/aftok/bippy.git
    commit: 97fda0368ae660239d1b9398d44530cd5b05eec3
  extra-dep: true
allow-newer: true
extra-deps:
  - snap-1.0.0.2
  - snaplet-postgresql-simple-1.0.2.0
  - haskoin-core-0.4.2
  - heist-1.0.1.0
  - map-syntax-0.2.0.2
  - murmur3-1.0.3
  - pbkdf-1.1.1.1
  - secp256k1-0.4.8
resolver: lts-8.5
local-bin-path: ./bin
