flags: {}
packages:
- '.'
- location:
    git: git@github.com:aftok/bippy.git
    commit: 6284d5fff3954e0e52d559298364035a220867af
  extra-dep: true
allow-newer: true
extra-deps:
- aeson-0.11.2.1
- base-orphans-0.5.4
- bytestring-builder-0.10.8.1.0
- call-stack-0.1.0
- haskoin-core-0.4.0
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- mmorph-1.0.9
- mono-traversable-0.10.2
- murmur3-1.0.1
- pbkdf-1.1.1.1
- postgresql-libpq-0.9.2.0
- postgresql-simple-0.5.2.1
- resource-pool-catchio-0.2.1.0
- secp256k1-0.4.5
- snaplet-postgresql-simple-0.6.0.4
- unix-compat-0.4.3.1
- vector-th-unbox-0.2.1.6
resolver: lts-5.3
