flags: {}
packages:
- '.'
- location:
    git: git@github.com:aftok/bippy.git
    commit: ddfc1bf0911351d0be51f33ea9e4166a24d2b19a
  extra-dep: true
allow-newer: true
extra-deps:
- heist-1.0.1.0
- map-syntax-0.2.0.1
- snap-1.0.0.1
- snaplet-postgresql-simple-1.0.1.0
resolver: lts-7.16
