flags: {}
packages:
- '.'
- location:
    git: https://github.com/aftok/bippy.git
    commit: 97fda0368ae660239d1b9398d44530cd5b05eec3
  extra-dep: true
allow-newer: true
extra-deps:
- heist-1.0.1.0
- map-syntax-0.2.0.1
- snap-1.0.0.1
- snaplet-postgresql-simple-1.0.1.0
resolver: lts-7.16
local-bin-path: ./bin
